# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:

  - name: Reload node_exporter to apply the new changes
    become: yes
    become_method: sudo
    raw: "systemctl daemon-reload"

  - name: Restart node_exporter
    become: yes
    become_method: sudo
    raw: "systemctl restart node_exporter"

  when: use_sudo | default(false)

- block:

  - name: Reload node_exporter to apply the new changes
    raw: "systemctl --user daemon-reload"

  - name: Restart node_exporter
    raw: "systemctl --user daemon-reload"

  when: not (use_sudo | default(false))